export const SET_VISIBILITY_FILTER = "SET_VISIBILITY_FILTER";
export const ADD_TODO = "ADD_TODO";
export const TOGGLE_TODO = "DELETE_TODO";
export const DELETE_TODO = "TOGGLE_TODO";
export const UPDATE_TODO = "UPDATE_TODO";